// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var MainActionButtonsView, StikerCollection, StikerModel, StikerView, mainActionButtons, stikerCollection;
    MainActionButtonsView = Backbone.View.extend({
      tagName: "div",
      el: "body",
      template: _.template($("#mainActionButtonsTemplate").html()),
      events: {
        "click #addStiker": "addStiker",
        "click #removeStiker.actionBut": "removeStiker",
        "click #removeStiker.actionBut_active": "endRemoveStiker"
      },
      render: function() {
        this.$el.append(this.template());
        return this;
      },
      addStiker: function() {
        var stikerModel, stikerView;
        stikerModel = new StikerModel;
        $("body").append('<div id="' + stikerModel.cid + '_wrapper"></div>');
        stikerView = new StikerView({
          model: stikerModel,
          el: "#" + stikerModel.cid + "_wrapper"
        });
        stikerCollection.add(stikerModel);
        return stikerView.render();
      },
      removeStiker: function() {
        $("#removeStiker").removeClass("actionBut").addClass("actionBut_active");
        return $(".stiker .del").show();
      },
      endRemoveStiker: function() {
        $("#removeStiker").removeClass("actionBut_active").addClass("actionBut");
        return $(".stiker .del").hide();
      }
    });
    StikerCollection = Backbone.Collection.extend({
      model: StikerModel
    });
    StikerModel = Backbone.Model.extend({
      top: 50,
      left: 300,
      zIndex: 1,
      color: "color1",
      shadow: "shadow",
      text: "hello",
      degX: 0,
      degY: 0,
      rot: 0,
      fontSize: 15,
      font: "Helvetica"
    });
    StikerView = Backbone.View.extend({
      tagName: "div",
      template: _.template($("#stikerView").html()),
      events: {
        "click .info": "dopSettings",
        "click .buttonDone": "dopSettings",
        "mousedown textarea": "moveStiker",
        "mouseup  textarea": "stopMoveStiker",
        "keyup textarea": "updateText",
        "click  li": "changeColor",
        "change #fontSizeSelect": "changeFontSize",
        "change #fontSelect": "changeFont",
        "click div.del": "removeStiker"
      },
      render: function() {
        this.$el.html(this.template(this.model));
        if ($("#removeStiker").hasClass("actionBut_active")) {
          $(".stiker .del").show();
        }
        return this;
      },
      updatePicture: function() {
        this.$el.empty();
        return this.render();
      },
      stopMoveStiker: function() {
        $("body").off("mousemove");
        return this.$el.find("textarea").focus();
      },
      moveStiker: function(e) {
        var startX, startY, view;
        $("div.stiker").css("z-index", 1);
        this.model.zIndex = 19000;
        this.updatePicture();
        view = this;
        startX = e.pageX;
        startY = e.pageY;
        return $("body").on("mousemove", function(eo) {
          var deltaX, deltaY;
          deltaX = startX - eo.pageX;
          deltaY = startY - eo.pageY;
          view.model.top = view.model.top - deltaY;
          view.model.left = view.model.left - deltaX;
          startX = eo.pageX;
          startY = eo.pageY;
          return view.updatePicture();
        });
      },
      updateText: function() {
        return this.model.text = $("#" + this.model.cid).find("textarea").val();
      },
      dopSettings: function() {
        if (this.model.rot === 1) {
          this.model.rot = 0;
        } else {
          this.model.rot = 1;
        }
        return this.updatePicture();
      },
      changeColor: function(e) {
        this.model.color = $(e.target).attr("color");
        return this.updatePicture();
      },
      changeFontSize: function(e) {
        this.model.fontSize = $(e.target).val();
        return this.updatePicture();
      },
      changeFont: function(e) {
        this.model.font = $(e.target).val();
        return this.updatePicture();
      },
      removeStiker: function() {
        stikerCollection.remove(this.model);
        return this.remove();
      }
    });
    stikerCollection = new StikerCollection;
    mainActionButtons = new MainActionButtonsView;
    return mainActionButtons.render();
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
